---
- hosts: web
  become: yes  # Run tasks with sudo
    - name: Install Apache HTTP Server
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache HTTP Server
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"
...
